# Generated by Django 5.0.3 on 2024-03-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dess', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
