# Generated by Django 5.0.3 on 2024-03-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='dess',
            new_name='desc',
        ),
    ]
